### ISSUE TITLE
IndexError: The shape of the mask [53005] at index 0 does not match the shape of the indexed tensor [1, 6] at index 0

### ISSUE THREAD

**Issue by TeaDrinkingGong** [city-super/Scaffold-GS#26]
When I used the script “single_train.sh",I encoutered this problem, but  I don't know the meanings of visible_mask.
Here is the detailed information：
Loading Test Cameras [08/03 19:24:59]
Initial voxel_size: 0.001 [08/03 19:25:07]
Number of points at initialisation :  53005 [08/03 19:25:07]
tensor([145.1975, 140.9139, 126.9154,  ...,   2.2357,  51.2508,  58.0233],
       device='cuda:0') <class 'torch.Tensor'> [08/03 19:25:07]
Training progress:   0%|                                                                                                                                                                         | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 526, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), dataset,  args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, wandb, logger)
  File "train.py", line 135, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background, visible_mask=voxel_visible_mask, retain_grad=retain_grad)
  File "/home/cvgluser/code/Scaffold-GS-main/gaussian_renderer/__init__.py", line 122, in render
    xyz, color, opacity, scaling, rot, neural_opacity, mask = generate_neural_gaussians(viewpoint_camera, pc, visible_mask, is_training=is_training)
  File "/home/cvgluser/code/Scaffold-GS-main/gaussian_renderer/__init__.py", line 26, in generate_neural_gaussians
    grid_scaling = pc.get_scaling[visible_mask]
**IndexError: The shape of the mask [53005] at index 0 does not match the shape of the indexed tensor [1, 6] at index 0**
Training progress:   0%|                                                                                                                                                                         | 0/30000 [00:00<?, ?it/s]

**Comment by inspirelt** [comment]
I have no idea about this error, please provide more context.
