### ISSUE TITLE
Train Error ! missing 2 arguments: 'kernel_size' and 'subpixel_offset'

### ISSUE THREAD

**Issue by goometasoft** [city-super/Scaffold-GS#39]
thank your Scaffold-GS , i like it very much !

```
python train.py  ^
-s E:\AI\A07\240310\win_cuda118\input\TaiDi_1280_35=5x7 ^
-m E:\AI\A07\240310\win_cuda118\input\TaiDi_1280_35=5x7\output ^
--voxel_size 0.001 --update_init_factor 16 ^
--appearance_dim 0 --ratio 1


Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
D:\conda\envs\cuda118\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\conda\envs\cuda118\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: D:\conda\envs\cuda118\lib\site-packages\lpips\weights\v0.1\vgg.pth
found tf board
2024-03-25 02:53:13,816 - INFO: args: Namespace(sh_degree=3, feat_dim=32, n_offsets=10, voxel_size=0.001, 
update_depth=3, update_init_factor=16, update_hierachy_factor=4, use_feat_bank=False, 
source_path='E:\\AI\\A07\\240310\\win_cuda118\\input\\TaiDi_1280_35=5x7', 
model_path='E:\\AI\\A07\\240310\\win_cuda118\\input\\TaiDi_1280_35=5x7\\output', images='images', 
resolution=-1, white_background=False, data_device='cuda', eval=False, lod=0, appearance_dim=0, lowpoly=False, 
ds=1, ratio=1, undistorted=False, add_opacity_dist=False, add_cov_dist=False, add_color_dist=False, 
iterations=30000, position_lr_init=0.0, position_lr_final=0.0, position_lr_delay_mult=0.01, 
position_lr_max_steps=30000, offset_lr_init=0.01, offset_lr_final=0.0001, offset_lr_delay_mult=0.01, 
offset_lr_max_steps=30000, feature_lr=0.0075, opacity_lr=0.02, scaling_lr=0.007, rotation_lr=0.002, 
mlp_opacity_lr_init=0.002, mlp_opacity_lr_final=2e-05, mlp_opacity_lr_delay_mult=0.01, 
mlp_opacity_lr_max_steps=30000, mlp_cov_lr_init=0.004, mlp_cov_lr_final=0.004, mlp_cov_lr_delay_mult=0.01, 
mlp_cov_lr_max_steps=30000, mlp_color_lr_init=0.008, mlp_color_lr_final=5e-05, mlp_color_lr_delay_mult=0.01, 
mlp_color_lr_max_steps=30000, mlp_featurebank_lr_init=0.01, mlp_featurebank_lr_final=1e-05, 
mlp_featurebank_lr_delay_mult=0.01, mlp_featurebank_lr_max_steps=30000, appearance_lr_init=0.05, 
appearance_lr_final=0.0005, appearance_lr_delay_mult=0.01, appearance_lr_max_steps=30000, percent_dense=0.01, 
lambda_dssim=0.2, start_stat=500, update_from=1500, update_interval=100, update_until=15000, 
min_opacity=0.005, success_threshold=0.8, densify_grad_threshold=0.0002, convert_SHs_python=False, 
compute_cov3D_python=False, debug=False, ip='127.0.0.1', port=6009, debug_from=-1, detect_anomaly=False, 
warmup=False, use_wandb=False, test_iterations=[7000, 30000], save_iterations=[7000, 30000, 30000], quiet=False, 
checkpoint_iterations=[], start_checkpoint=None, gpu='0')

$CUDA_VISIBLE_DEVICES
2024-03-25 02:53:13,825 - INFO: using GPU 0
2024-03-25 02:53:13,827 - INFO: save code failed~
2024-03-25 02:53:13,827 - INFO: Optimizing E:\AI\A07\240310\win_cuda118\input\TaiDi_1280_35=5x7\output
Output folder: E:\AI\A07\240310\win_cuda118\input\TaiDi_1280_35=5x7\output [25/03 02:53:13]
Reading camera 35/35 [25/03 02:53:13]
start fetching data from ply file [25/03 02:53:13]
Loading Training Cameras [25/03 02:53:13]
Loading Test Cameras [25/03 02:53:14]
Initial voxel_size: 0.001 [25/03 02:53:14]
Number of points at initialisation :  5579 [25/03 02:53:14]
Training progress:   0%|                                                                                                             | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  
File "E:\AI\A07\240310\win_cuda118\train.py", line 536, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), dataset,  args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, wandb, logger)
  
File "E:\AI\A07\240310\win_cuda118\train.py", line 136, in training
    voxel_visible_mask = prefilter_voxel(viewpoint_cam, gaussians, pipe,background)
  
File "E:\AI\A07\240310\win_cuda118\gaussian_renderer\__init__.py", line 203, in prefilter_voxel
    raster_settings = GaussianRasterizationSettings(

TypeError: <lambda>() missing 2 required positional arguments: 'kernel_size' and 'subpixel_offset'

Training progress:   0%|                                                                                                             | 0/30000 [00:00<?, ?it/s]
```

**Comment by tongji-rkr** [comment]
I guess you didn't recompile diff-gaussian-rasterization before training.

**Comment by LiHaodong0217** [comment]
i meet the same problem,and i  go to recompile diff-gaussian-rasterization before training
so it can run,thank you!
