### ISSUE TITLE
Meet an error.

### ISSUE THREAD

**Issue by Yuhuoo** [city-super/Scaffold-GS#65]
I have meet an error. How could I solve it?

(scaffold_gs) ga@test-4U-GPU-Server:~/code/Scaffold-GS$ bash single_train.sh
0
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    import torchvision
  File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets
  File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import KittiFlow, Sintel, FlyingChairs, FlyingThings3D, HD1K
  File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/torchvision/datasets/_optical_flow.py", line 13, in <module>
    from .utils import verify_str_arg
  File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 21, in <module>
    import requests
  File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/requests/__init__.py", line 164, in <module>
    from .api import delete, get, head, options, patch, post, put, request
  File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/requests/api.py", line 11, in <module>
    from . import sessions
  File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/requests/sessions.py", line 15, in <module>
    from .adapters import HTTPAdapter
  File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/requests/adapters.py", line 60, in <module>
    from urllib3.contrib.socks import SOCKSProxyManager
  File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/urllib3/contrib/socks.py", line 75, in <module>
    class _TYPE_SOCKS_OPTIONS(typing.TypedDict):
AttributeError: module 'typing' has no attribute 'TypedDict

**Comment by inspirelt** [comment]
maybe you can update the related dependency.

**Comment by Ysc-shark** [comment]
> I have meet an error. How could I solve it?
> 
> (scaffold_gs) ga@test-4U-GPU-Server:~/code/Scaffold-GS$ bash single_train.sh 0 Traceback (most recent call last): File "train.py", line 24, in import torchvision File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/torchvision/**init**.py", line 5, in from torchvision import datasets File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/torchvision/datasets/**init**.py", line 1, in from ._optical_flow import KittiFlow, Sintel, FlyingChairs, FlyingThings3D, HD1K File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/torchvision/datasets/_optical_flow.py", line 13, in from .utils import verify_str_arg File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 21, in import requests File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/requests/**init**.py", line 164, in from .api import delete, get, head, options, patch, post, put, request File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/requests/api.py", line 11, in from . import sessions File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/requests/sessions.py", line 15, in from .adapters import HTTPAdapter File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/requests/adapters.py", line 60, in from urllib3.contrib.socks import SOCKSProxyManager File "/home/ga/software/anaconda3/envs/scaffold_gs/lib/python3.7/site-packages/urllib3/contrib/socks.py", line 75, in class _TYPE_SOCKS_OPTIONS(typing.TypedDict): AttributeError: module 'typing' has no attribute 'TypedDict

I had the same problem and I haven't solved it yet.Have you found solution?

**Comment by tongji-rkr** [comment]
Two Solution:
- Update python to 3.8+
- Reinstall urllib3=2.0.7

**Comment by Ysc-shark** [comment]
> Two Solution:
> 
> * Update python to 3.8+
> * Reinstall urllib3=2.0.7

Thanks for prompt reply.I try second sulution and it works.
Additionly,I install package opencv-python and jaxtyping,which are not included in environment.yml,and the program works.
