### ISSUE TITLE
Error about scene type: assert False, "Could not recognize scene type!" AssertionError: Could not recognize scene type!

### ISSUE THREAD

**Issue by Santasu28** [city-super/Scaffold-GS#86]
When I run train_db.sh , i meet the following error messege:

(scaffold_gs) root@autodl-container-1b3442a671-d472fe41:~/autodl-tmp/Scaffold-GS# bash train_db.sh
0
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
/root/miniconda3/envs/scaffold_gs/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/root/miniconda3/envs/scaffold_gs/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /root/miniconda3/envs/scaffold_gs/lib/python3.7/site-packages/lpips/weights/v0.1/vgg.pth
not found tf board
2024-10-29 13:04:00,513 - INFO: args: Namespace(add_color_dist=False, add_cov_dist=False, add_opacity_dist=False, appearance_dim=0, appearance_lr_delay_mult=0.01, appearance_lr_final=0.0005, appearance_lr_init=0.05, appearance_lr_max_steps=30000, checkpoint_iterations=[], compute_cov3D_python=False, convert_SHs_python=False, data_device='cuda', debug=False, debug_from=-1, densify_grad_threshold=0.0002, detect_anomaly=False, ds=1, eval=True, feat_dim=32, feature_lr=0.0075, gpu='-1', images='images', ip='127.0.0.1', iterations=30000, lambda_dssim=0.2, lod=0, lowpoly=False, min_opacity=0.005, mlp_color_lr_delay_mult=0.01, mlp_color_lr_final=5e-05, mlp_color_lr_init=0.008, mlp_color_lr_max_steps=30000, mlp_cov_lr_delay_mult=0.01, mlp_cov_lr_final=0.004, mlp_cov_lr_init=0.004, mlp_cov_lr_max_steps=30000, mlp_featurebank_lr_delay_mult=0.01, mlp_featurebank_lr_final=1e-05, mlp_featurebank_lr_init=0.01, mlp_featurebank_lr_max_steps=30000, mlp_opacity_lr_delay_mult=0.01, mlp_opacity_lr_final=2e-05, mlp_opacity_lr_init=0.002, mlp_opacity_lr_max_steps=30000, model_path='outputs/blending/playroom/baseline/2024-10-29_13:03:54', n_offsets=10, offset_lr_delay_mult=0.01, offset_lr_final=0.0001, offset_lr_init=0.01, offset_lr_max_steps=30000, opacity_lr=0.02, percent_dense=0.01, port=10765, position_lr_delay_mult=0.01, position_lr_final=0.0, position_lr_init=0.0, position_lr_max_steps=30000, quiet=False, ratio=1, resolution=-1, rotation_lr=0.002, save_iterations=[30000, 30000], scaling_lr=0.007, sh_degree=3, source_path='data/blending/playroom', start_checkpoint=None, start_stat=500, success_threshold=0.8, test_iterations=[30000], undistorted=False, update_depth=3, update_from=1500, update_hierachy_factor=4, update_init_factor=16, update_interval=100, update_until=15000, use_feat_bank=False, use_wandb=False, voxel_size=0.005, warmup=False, white_background=False)
Backup Finished!
2024-10-29 13:04:00,741 - INFO: Optimizing outputs/blending/playroom/baseline/2024-10-29_13:03:54
Output folder: outputs/blending/playroom/baseline/2024-10-29_13:03:54 [29/10 13:04:00]
Tensorboard not available: not logging progress [29/10 13:04:00]
Traceback (most recent call last):
  File "train.py", line 527, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), dataset,  args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, wandb, logger)
  File "train.py", line 87, in training
    scene = Scene(dataset, gaussians, ply_path=ply_path, shuffle=False)
  File "/root/autodl-tmp/Scaffold-GS/scene/__init__.py", line 50, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!

Could you give me some advice about how to solve it?

**Comment by inspirelt** [comment]
Seems that your data format does not match with the requirement. Please check it.

**Comment by KZI-22** [comment]
Excuse me.Please share that how did you solve this error.
