### ISSUE TITLE
Why an AttributeError occured:  'GroupParams' object has no attribute 'percent_dense'

### ISSUE THREAD

**Issue by realCCHstudio** [city-super/Scaffold-GS#94]
I can see class GroupParams in the file arguments/__init__.py is empty, (nothing but `pass`)but when I run train.sh, it tells me this error.
The full console is listed behind:
train_bungee.sh: line 8: ulimit: open files: cannot modify limit: Operation not permitted
$CUDA_VISIBLE_DEVICES
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
C:\Users\hp\.conda\envs\scaffold_gs\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\hp\.conda\envs\scaffold_gs\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: C:\Users\hp\.conda\envs\scaffold_gs\lib\site-packages\lpips\weights\v0.1\vgg.pth
C:\Users\hp\.conda\envs\scaffold_gs\lib\site-packages\lpips\lpips.py:107: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(model_path, map_location='cpu'), strict=False)
found tf board
2024-12-10 19:01:21,995 - INFO: args: Namespace(sh_degree=3, feat_dim=32, n_offsets=10, voxel_size=0.0, update_depth=3, update_init_factor=128, update_hierachy_factor=4, use_feat_bank=False, source_path='data/bungeenerf/amsterdam', model_path='outputs/bungeenerf/amsterdam/baseline/2024-12-10_19:01:07', images='images', resolution=-1, white_background=False, data_device='cuda', eval=True, lod=30, appearance_dim=0, lowpoly=False, ds=1, ratio=1, undistorted=False, add_opacity_dist=False, add_cov_dist=False, add_color_dist=False, iterations=30000, position_lr_init=0.0, position_lr_final=0.0, position_lr_delay_mult=0.01, position_lr_max_steps=30000, convert_SHs_python=False, compute_cov3D_python=False, debug=False, ip='127.0.0.1', port=14097, debug_from=-1, detect_anomaly=False, warmup=False, use_wandb=False, test_iterations=[30000], save_iterations=[30000, 30000], quiet=False, checkpoint_iterations=[], start_checkpoint=None, gpu='-1')
2024-12-10 19:01:21,996 - INFO: save code failed~
2024-12-10 19:01:21,996 - INFO: Optimizing outputs/bungeenerf/amsterdam/baseline/2024-12-10_19:01:07
Output folder: outputs/bungeenerf/amsterdam/baseline/2024-12-10_19-01-07 [10/12 19:01:22]
Reading camera 161/161 [10/12 19:01:22]
using lod, using eval [10/12 19:01:22]
test_cam_infos: 31 [10/12 19:01:22]
start fetching data from ply file [10/12 19:01:23]
Loading Training Cameras [10/12 19:01:23]
[ INFO ] Large input images (>1.6K pixels width), rescaling to 1.6K.
 Specify '--resolution/-r' as 1 if rescaling is not desired. [10/12 19:01:23]
$CUDA_VISIBLE_DEVICES
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
C:\Users\hp\.conda\envs\scaffold_gs\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\hp\.conda\envs\scaffold_gs\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: C:\Users\hp\.conda\envs\scaffold_gs\lib\site-packages\lpips\weights\v0.1\vgg.pth
C:\Users\hp\.conda\envs\scaffold_gs\lib\site-packages\lpips\lpips.py:107: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(model_path, map_location='cpu'), strict=False)
found tf board
2024-12-10 19:01:42,458 - INFO: args: Namespace(sh_degree=3, feat_dim=32, n_offsets=10, voxel_size=0.0, update_depth=3, update_init_factor=128, update_hierachy_factor=4, use_feat_bank=False, source_path='data/bungeenerf/bilbao', model_path='outputs/bungeenerf/bilbao/baseline/2024-12-10_19:01:27', images='images', resolution=-1, white_background=False, data_device='cuda', eval=True, lod=30, appearance_dim=0, lowpoly=False, ds=1, ratio=1, undistorted=False, add_opacity_dist=False, add_cov_dist=False, add_color_dist=False, iterations=30000, position_lr_init=0.0, position_lr_final=0.0, position_lr_delay_mult=0.01, position_lr_max_steps=30000, convert_SHs_python=False, compute_cov3D_python=False, debug=False, ip='127.0.0.1', port=23009, debug_from=-1, detect_anomaly=False, warmup=False, use_wandb=False, test_iterations=[30000], save_iterations=[30000, 30000], quiet=False, checkpoint_iterations=[], start_checkpoint=None, gpu='-1')
2024-12-10 19:01:42,478 - INFO: save code failed~
2024-12-10 19:01:42,478 - INFO: Optimizing outputs/bungeenerf/bilbao/baseline/2024-12-10_19:01:27
Output folder: outputs/bungeenerf/bilbao/baseline/2024-12-10_19-01-27 [10/12 19:01:42]
Reading camera 129/129 [10/12 19:01:44]
using lod, using eval [10/12 19:01:44]
test_cam_infos: 31 [10/12 19:01:44]
start fetching data from ply file [10/12 19:01:44]
Loading Training Cameras [10/12 19:01:44]
[ INFO ] Large input images (>1.6K pixels width), rescaling to 1.6K.
 Specify '--resolution/-r' as 1 if rescaling is not desired. [10/12 19:01:44]
$CUDA_VISIBLE_DEVICES
Loading Test Cameras [10/12 19:01:49]
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
C:\Users\hp\.conda\envs\scaffold_gs\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\hp\.conda\envs\scaffold_gs\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: C:\Users\hp\.conda\envs\scaffold_gs\lib\site-packages\lpips\weights\v0.1\vgg.pth
C:\Users\hp\.conda\envs\scaffold_gs\lib\site-packages\lpips\lpips.py:107: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(model_path, map_location='cpu'), strict=False)
Initial voxel_size: 3.5121400287607685e-05 [10/12 19:02:08]
$CUDA_VISIBLE_DEVICES
Number of points at initialisation :  124818 [10/12 19:02:10]
Traceback (most recent call last):
  File "D:\DevelopFiles\Scaffold_GS_cch\Scaffold-GS\train.py", line 655, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), dataset,  args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, wandb, logger)
  File "D:\DevelopFiles\Scaffold_GS_cch\Scaffold-GS\train.py", line 119, in training
    gaussians.training_setup(opt)
  File "D:\DevelopFiles\Scaffold_GS_cch\Scaffold-GS\scene\gaussian_model.py", line 342, in training_setup
    self.percent_dense = training_args.percent_dense
AttributeError: 'GroupParams' object has no attribute 'percent_dense'
found tf board

**Comment by realCCHstudio** [comment]
the dataset I used is bungee, and my runtime environment is on Windows.(due to the log filename is unavailable on windows, I change ':' to '_', but I suppose it doesn't matter to the program)
